name: Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install .NET Core SDK 5.0.202
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
    
      - name: Install Dotnet Tools
        run: dotnet tool restore
        
      - name: Run Fake
        run: dotnet fake build
